### ISSUE TITLE
clipboard method

### ISSUE THREAD

**Issue by dreamlivemeng** [zsavely/RxClipboard#10]
clipboard method  is private,why not set public?

```
 @CheckResult @NonNull
  private static ClipboardManager clipboard(@NonNull Context context) {
    return (ClipboardManager) context.getSystemService(Context.CLIPBOARD_SERVICE);
  }
```

**Comment by zsavely** [comment]
This method is used internally. And wasn't intended to be a part of the public API. Why would you want it to be public?

**Comment by dreamlivemeng** [comment]
I would like to directly copy or paste text, need to use it(ClipboardManager).Rather than merely monitoring changes in the clipboard.

**Comment by zsavely** [comment]
You can copy this method without worries because `ClipboardManager` is a part of Android API.

``` java
import android.content.ClipboardManager;
import android.content.Context;
import android.support.annotation.CheckResult;
import android.support.annotation.NonNull;

@CheckResult @NonNull
public static ClipboardManager clipboard(@NonNull Context context) {
  return (ClipboardManager) context.getSystemService(Context.CLIPBOARD_SERVICE);
}
```

**Comment by dreamlivemeng** [comment]
all right,thank you! I know it is a part of Andorid API.I think I can through clipboard(context) to get to ClipboardManager,so I hope it is public.But now I think you're right, I should use it .

```
ClipboardManager clipboardManager = (ClipboardManager) getSystemService(CLIPBOARD_SERVICE);
```
